# Generated by Django 5.1.3 on 2024-11-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersForTkn',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ies.users_for_tkn',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
